version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: anda
      POSTGRES_PASSWORD: anda123
      POSTGRES_DB: anda_db
    networks:
      - my_network
    ports:
      - "5432:5432"

  dapeps-go:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - my_network

  # tests:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.test
  #   volumes:
  #     - .:/app
  #   command: ["ginkgo"]    

networks:
  my_network:     
